language: R
cache: packages

bioc_required: true
bioc_packages:
  - BiocInstaller

before_script:
    - git config --global user.name "travis"
    - git config --global user.email "travis@example.org"

after_success:
  - Rscript -e 'covr::codecov()'
