language: R
cache: packages
sudo: false
bioc_required: true
warnings_are_errors: true
before_script:
    - git config --global user.name "travis"
    - git config --global user.email "travis@example.org"

bioc_packages:
  - BiocInstaller

after_success:
  - Rscript -e 'covr::codecov()'
