language: r
sudo: required
bioc_required: true
warnings_are_errors: true

r_binary_packages:
  - XML
  - Rcpp
  - knitr

r_github_packages:
  - rstudio/rmarkdown
  - hadley/testthat

bioc_packages:
  - BiocInstaller
